### ISSUE TITLE
When deploying to stg using .env file returns UnhandledPromiseRejectionWarning: Error: null

### ISSUE THREAD

**Issue by jessen-eg** [jenssimon/sfcc-deploy#67]
HOST=staging.na01.****redacted****.demandware.net
HOSTNAME=cert.staging.na01.****redacted****.demandware.net
CLIENT_ID=****redacted****
VERSION=v1.1.65
CLIENT_SECRET=****redacted****
P12=./sfcc/eg.p12
PASSPHRASE=****redacted****
ACTIVATE_CODE_VERSION=True

`'use strict';
var sfccDeploy = require('sfcc-deploy').default;
var sfcc = require('sfcc-ci');
require('dotenv').config();
var version = process.env.VERSION;
var config = {
    host: process.env.HOST,
    hostname: process.env.HOSTNAME,
    clientId: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    p12: process.env.P12, // two factor authentication
    passphrase: process.env.PASSPHRASE // two factor authentication
};
var activateCodeVersion = {
    name: function (params) {
        return 'Activating code version: ' + params.options.version;
    },
    condition: 'activateCodeVersion', // the flag name needed to active the task
    emoji: 'fast_forward',
    fn: function (params) {
        if (!params.activateCodeVersion) {
            return;
        }
        sfcc.code.activate(config.host, version, params.token, function (error) {
            if (error) {
                console.log(error);
            }
        });
    }
};
sfccDeploy({
    additionalSteps: [
        activateCodeVersion
    ],
    activateCodeVersion: true,
    credentials: config,
    version: version,
    root: './'
});`

when i run this script with .env values i'm encountering this error

`(node:80615) UnhandledPromiseRejectionWarning: Error: null
    at Request._callback (/Users/****redacted****/Documents/****redacted****/eg_sfcc/node_modules/sfcc-ci/lib/auth.js:692:22)
    at Request.self.callback (/Users/jesse/Documents/****redacted****/eg_sfcc/node_modules/sfcc-ci/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/Users/****redacted****/Documents/****redacted****/eg_sfcc/node_modules/sfcc-ci/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/Users/****redacted****/Documents/****redacted****/eg_sfcc/node_modules/sfcc-ci/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:80615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:80615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

but when i hardcode the values within my script it works fine i also verified that the no null values are being passed in

**Comment by jenssimon** [comment]
Hi @jessen-eg 

I missed to mention in README that the `sfccDeploy` function returns a `Promise`. So correct usage would look like:

```typescript
import sfccDeploy from 'sfcc-deploy';

// ...

try {
  await sfccDeploy({
    credentials: config,
    version,

    root: './dist/', // default: './dist/'
  });
} catch (e) {
  console.error('error on deploy', e);
}
```

I will update the documentation.
